---
fail_fast: false
default_stages:
  - commit
  - push

repos:
  - repo: https://github.com/thlorenz/doctoc
    rev: v2.2.0
    hooks:
      - id: doctoc
        args:
          - --update-only
          - --maxlevel
          - "3"
          - --github
          - --notitle

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
        args:
          - --maxkb=100
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-symlinks
      - id: check-xml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: fix-byte-order-marker
      - id: mixed-line-ending
        args:
          - --fix=auto
      - id: trailing-whitespace
        args:
          - --markdown-linebreak-ext=md
      - id: no-commit-to-branch
        args: ["--branch", "main"]

  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.4
    hooks:
      - id: remove-crlf
      - id: remove-tabs

  - repo: https://github.com/sirosen/fix-smartquotes
    rev: 0.2.0
    hooks:
      - id: fix-smartquotes

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.37.0
    hooks:
      - id: markdownlint-fix
        args:
          - --config
          - .markdownlint.yaml

  - repo: https://github.com/k8s-at-home/sops-pre-commit
    rev: v2.1.1
    hooks:
      - id: forbid-secrets

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        args:
          - --ignore-path
          - .prettierignore
          - --config
          - .prettierrc.yaml

  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.1
    hooks:
      - id: gitleaks-docker
