name: publish static content to Github Pages

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - pages/*

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  publish:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout
        uses: actions/checkout@v4.1.1

      # https://github.com/marketplace/actions/configure-github-pages
      - name: setup Pages
        uses: actions/configure-pages@v3.0.6

      # https://github.com/marketplace/actions/upload-github-pages-artifact
      - name: upload artifact
        uses: actions/upload-pages-artifact@v2.0.0
        with:
          # Upload entire repository
          path: pages

      # https://github.com/marketplace/actions/deploy-github-pages-site
      - name: deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2.0.5
